### ISSUE TITLE
Explain and link to the Bundler slack

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-site#235]
We have a working Slack inviter (hooray) that lives at http://slack.bundler.io. We should mention that the Slack exists, explain that that is where we coordinate work on Bundler, RubyGems, and RubyGems.org, and then link to the inviter! Something like the old "how to contact the community" paragraph on the previous site design.

**Comment by icstunna** [comment]
@indirect I believe I have now solved the problem in my latest pull request

https://github.com/bundler/bundler-site/pull/239

The link can now be viewed as part of the 'Get Involved' section at the bottom of the '/v1.12#getting-started/' path of the bundler.io site. Also, as per our discussion, the IRC link was replaced by the Slack link since the IRC channel no longer seems to be in fashion.

Please let me know if you have any comments, questions or clarifications.

**Comment by LynnCo** [comment]
Closed via https://github.com/bundler/bundler-site/pull/239
