### ISSUE TITLE
[RFC] Homepage improvements

### ISSUE THREAD

**Issue by colby-swandale** [bundler/bundler-site#281]
One thing that bothers me about the homepage was that the "Getting Started" section feels a bit incomplete.

After specifying your deps in the Gemfile and running `bundle install` i immediately ask the question. Now what? I think the Getting Started section could be expand on how to use Bundler to load gems in a ruby script (example provided, see below) and provide links to the necessary documentation.

Here is an example screenshot of the change, this is no way complete and text could be a lot better. I just want to test the water and see how other people feel.
![bundler the best way to manage a ruby application s gems](https://cloud.githubusercontent.com/assets/996377/20999543/5bedae94-bd69-11e6-85be-9477d512104f.png)

I have also added a little `What is the gem command?` directly below the `gem install ...` which links to http://guides.rubygems.org/rubygems-basics. This i think is a good thing for people that is really new to ruby and is unfamiliar with the available tooling.

Let me know what you think.

**Comment by indirect** [comment]
I think it probably makes sense to expand the homepage a bit again... I think we probably cut it down a little bit too far when we redesigned. The old homepage had slowly grown into [everything here](http://bundler.io/v1.13/) and that was definitely too much.

The reason that we've never had an example of using a bundled gem from a ruby script on the homepage before is that, statistically, almost everyone viewing the homepage will be using their bundled gem inside a rails app. I'm pretty sure (based on past experience) that adding a section like the one that you've mocked up here would lead to Rails devs putting a bunch of requires in their Rails app in random places, and we would like to avoid that. Ultimately, we'll probably want some sort of "possible next steps" set of options on the homepage, with things like "Use Bundler with Rails", "Use Bundler with a Ruby script", and "Create your own gem with Bundler".

/cc @feministy your thoughts on this would also be super welcome!

**Comment by feministy** [comment]
We want the homepage to have the vital information that _most_ of our users are looking for. Bundler has a lot of users and a lot of different uses! This means we have the constant battle of too much and too little info. So to @indirect's point - we do want to serve this primary use case the most, and I agree @colby-swandale that we want to surface info about the other uses as well.

I'd advocate for keeping the details about these users off the homepage to keep it clear... especially for folks new to Bundler - or even just Ruby or Rails! - the line between "what you need for your app" versus "what Bundler can do" might not be super clear in this scenario.

>Ultimately, we'll probably want some sort of "possible next steps" set of options on the homepage, with things like "Use Bundler with Rails", "Use Bundler with a Ruby script", and "Create your own gem with Bundler".

I would love to expand on all three of these with dedicated guides! I've already got some stuff in progress for creating gems using Bundler ✏️ 

Once we get to the point where we have docs for all 3 of these, it might be nice to present them all on the homepage somehow with the primary use case (being Rails and a Gemfile) as the default visible. I'm no designer, so I offer no suggestions on how to display this info 😄

But! In the short term! Two small changes that would help both goals:

- Under "getting started", specify that this is for use with applications (Rails, etc)
- At the end of the docs, link out to to existing resources for using Bundler to create gems and with Ruby scripts

**Comment by hmistry** [comment]
@feministy I was discussing this with @colby-swandale earlier and had similar thoughts as you, although you've framed it a lot better... basically perhaps the more detailed guide for new users needs to be a separate page.

I discovered we have some more detailed guides on how to use bundler - see if these are appropriate for beginners:  http://bundler.io/v1.12/#getting-started or http://bundler.io/rationale.html#summary

One thing I had mentioned in our conversation was, if you tried to think why a new user would be left with the thought of "ok I'm done installing, now what?", it's because we failed to communicate what bundler is and its role in a project. For example, when I look at the home page, my eyes go to hero shot and then to the Getting Started section. This means I skip the 3 lines of text that tells me what bundler is... this body text is not visually strong to grab my attention before getting started section. Maybe it needs a small header stating "What is bundler?" or "Bundler - the ruby gem manager for projects" or something to get my attention before the getting started section.

Looking at the getting started section, some thoughts I have are around playing with the sentences to better explain things to a user. Some examples are:
1. "Getting started with bundler is easy! Bundler is a ruby gem and needs to be installed first. Open a terminal window and run this command:"
2. "In your project's root folder, specify the gems needed for your project in a Gemfile like this:"
3. "Use bundler to install all of the required gems in your Gemfile"
4. "And now your project will have the correct gems available to it... happy coding"
